# Generated by Django 6.0.1 on 2026-02-05 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('PHISHING', 'Phishing Simulation'), ('PASSWORD', 'Password Security'), ('GENERAL', 'General Hygiene')], max_length=50)),
                ('xp_reward', models.IntegerField(default=50)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDrillProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drills.drill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drill_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
