# Generated by Django 6.0.1 on 2026-02-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drill',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed')], default='RUNNING', max_length=20),
        ),
    ]
