# Generated by Django 6.0.1 on 2026-02-07 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0002_drill_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrillQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('points', models.IntegerField(default=10)),
                ('order', models.IntegerField(default=0)),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='drills.drill')),
            ],
        ),
        migrations.CreateModel(
            name='DrillChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True, help_text='AI explanation for why this choice is right/wrong')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='drills.drillquestion')),
            ],
        ),
    ]
