# Generated by Django 6.0.1 on 2026-02-07 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drills', '0003_drillquestion_drillchoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrillAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('is_passed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('drill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='drills.drill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drill_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
