# Generated by Django 6.0.1 on 2026-02-03 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(choices=[('SENTRY', 'Sentry (Network)'), ('ANALYST', 'Analyst (Cognitive)'), ('GUARDIAN', 'Guardian (Identity)')], max_length=50)),
                ('severity', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=2)),
                ('target_url', models.URLField(max_length=500)),
                ('threat_signature', models.CharField(help_text='e.g. Homoglyph Attack, Ransomware.B', max_length=255)),
                ('ai_explanation', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threat_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
