# Generated by Django 6.0.1 on 2026-02-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatevent',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='threatevent',
            name='threat_signature',
            field=models.CharField(help_text='e.g. Homoglyph Attack', max_length=255),
        ),
    ]
