# Generated by Django 6.0.1 on 2026-02-06 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentry', '0002_threatevent_is_resolved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentry_paranoia_level', models.IntegerField(default=75, help_text='1-100 sensitivity')),
                ('block_new_domains', models.BooleanField(default=True)),
                ('detect_homoglyphs', models.BooleanField(default=True)),
                ('allow_bypass', models.BooleanField(default=False)),
                ('simple_explanations', models.BooleanField(default=True)),
                ('gamified_quizzes', models.BooleanField(default=True)),
                ('credential_reuse_monitor', models.BooleanField(default=True)),
                ('dark_web_scan', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
