# Generated by Django 6.0.1 on 2026-02-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentry', '0004_auditlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threatevent',
            old_name='target_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='threatevent',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='threatevent',
            name='ai_explanation',
        ),
        migrations.RemoveField(
            model_name='threatevent',
            name='is_resolved',
        ),
        migrations.RemoveField(
            model_name='threatevent',
            name='severity',
        ),
        migrations.AddField(
            model_name='threatevent',
            name='status',
            field=models.CharField(default='BLOCKED', max_length=50),
        ),
        migrations.AddField(
            model_name='threatevent',
            name='type',
            field=models.CharField(choices=[('BLOCK', 'Blocked Request'), ('BREACH', 'Dark Web Breach'), ('PHISHING', 'Phishing Attempt')], default='BLOCK', max_length=20),
        ),
        migrations.AlterField(
            model_name='threatevent',
            name='threat_signature',
            field=models.CharField(max_length=255),
        ),
    ]
