# Generated by Django 6.0.1 on 2026-02-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentry', '0005_rename_target_url_threatevent_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatevent',
            name='ai_explanation',
            field=models.TextField(blank=True, help_text='Reasoning for the block', null=True),
        ),
    ]
