# Generated by Django 6.0.1 on 2026-02-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='risk_score',
            field=models.IntegerField(default=100, help_text='Start at 100, decrease on threats'),
        ),
    ]
