# Generated by Django 6.0.1 on 2026-02-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_institutionapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extension_installed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_extension_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='streak_count',
            field=models.IntegerField(default=0, help_text='Consecutive days without incidents'),
        ),
        migrations.AlterField(
            model_name='user',
            name='risk_score',
            field=models.IntegerField(default=100),
        ),
    ]
