# Generated by Django 6.0.1 on 2026-02-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_extension_installed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, help_text='e.g. Computer Science', max_length=100, null=True),
        ),
    ]
