# Generated by Django 6.0.1 on 2026-02-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_institution_admin_email_institution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='xp',
            field=models.IntegerField(default=0, help_text='Experience Points from drills'),
        ),
    ]
